apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: 280296955917.dkr.ecr.us-east-2.amazonaws.com/fulcrum-js
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    dateTime:
      format: 2006-01-02_15-04-05.999_MST
      timezone: Local
  platforms:
    - linux/amd64
  local:
    tryImportMissing: true
    useBuildkit: true
    concurrency: 3
deploy: {}
profiles:
  - name: ci
    build:
      tagPolicy:
        gitCommit:
          variant: AbbrevCommitSha
          ignoreChanges: true
  - name: kaniko
    build:
      cluster:
        serviceAccount: ci-pipeline
        namespace: ci
        kanikoImage: 280296955917.dkr.ecr.us-east-2.amazonaws.com/kaniko:latest
        # volumes:
        # - name: npmrc
        #   secret:
        #     secretName: secret-npmrc
      artifacts:
        - image: 280296955917.dkr.ecr.us-east-2.amazonaws.com/fulcrum-js
          kaniko:
            dockerfile: Dockerfile
            useNewRun: true
            image: 280296955917.dkr.ecr.us-east-2.amazonaws.com/kaniko:latest
          # volumeMounts:
          # - mountPath: /usr/local/etc/npmrc
          #   name: npmrc
          #   subPath: .npmrc
