---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: ecr-sampleAPP
  labels:
    tf.weave.works/composite: ecr
    kust-include-region: true
spec:
  path: ecr
  values:
    name: sampleAPP
    region:
  sourceRef:
    kind: OCIRepository
    name: terraform-modules
    namespace: flux-system
  approvePlan: auto
  retryInterval: 4h
  interval: 10h0m
  destroyResourcesOnDeletion: false
  writeOutputsToSecret:
    name: ecr-sampleAPP
